version: 2
updates:

  - package-ecosystem: "maven"
    directories:
      - "/src"
      - "/target"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
    schedule:
      interval: "monthly"
    target-branch: "main"
    groups:
      guide-dependencies-maven:
        patterns:
          - "*"